system {
    host-name staging-in-progress;
    time-zone America/Los_Angeles;
    root-authentication {
        encrypted-password "$6$NgvmIJVf$6OJJ2cMgNKEAQDmmRUQZ.vf7x4RXCuj8U/sNUW.6dXm/JW0CERb1Xtm59ejsvCOb46QNETgmg6I722UCPn1Yf0"; ## SECRET-DATA
    }
    login {
        class FULL-ACCESS {
            idle-timeout 30;
            login-alarms;
            permissions all;
        }
        class READ-ACCESS {
            idle-timeout 30;
            login-alarms;
            permissions [ firewall interface network routing system view view-configuration ];
            allow-commands "show log|clear interfaces statistics";
            deny-commands "(ssh)|(telnet)";
        }
        user admin {
            uid 2001;
            class FULL-ACCESS;
            authentication {
                encrypted-password "$6$NgvmIJVf$6OJJ2cMgNKEAQDmmRUQZ.vf7x4RXCuj8U/sNUW.6dXm/JW0CERb1Xtm59ejsvCOb46QNETgmg6I722UCPn1Yf0"; ## SECRET-DATA
            }
        }
        user remote {
            full-name "TACACS Account for Shared Access";
            uid 2000;
            class FULL-ACCESS;
        }
    }
    services {
        xnm-clear-text;             /* Junos XML protocol server - required for jcs:open() in SLAX scripts */
        netconf {
            ssh;
            rfc-compliant;
            yang-compliant;
        }
    }
    syslog {
        file auth.log {
            authorization any;
            archive size 1m files 1 world-readable;
        }
        file bpdu-events.log {
            any any;
            match "(.*BPDU*.|.*L2CPD*.|.*TOPO_CH*.|.*STP.*)";
            archive size 1m files 3 world-readable;
        }
        file config.log {
            change-log info;
        }
        file daemon.log {
            daemon info;
            archive size 1m files 1 world-readable;
        }
        file firewall.log {
            firewall any;
            archive size 5m files 3 world-readable;
        }
        file health.log {
            any info;
            match .*_HEALTHMONITOR_.*;
            archive size 1m files 1 world-readable;
        }
        file interactive-commands {
            interactive-commands any;
        }
        file interfaces.log {
            any info;
            match .*SNMP_TRAP_LINK.*;
            archive size 1m files 3 world-readable;
        }
        file login-attempts {
            authorization any;
            match "(login_failed | login_pam_authentication_error | login_pam_error | login_timed_out | sshd_login_failed)";
        }
        file messages {
            any notice;
            authorization info;
            match "!SNMPD_AUTH_FAILURE";
            archive size 5m files 3 world-readable;
        }
        file security.log {
            authorization info;
            interactive-commands info;
            match ".*UI_COMMIT:.*\n.*UI_CMDLINE_READ_LINE.*\n.*UI_LOAD_EVENT.*\n.*password.*";
            archive size 3m files 3 world-readable;
        }
        time-format year millisecond;
    }
}
interfaces {
    me0 {
        unit 0 {
            family inet {
                dhcp {
                    vendor-id juniper-access;
                }
            }
        }
    }
}
event-options {
    generate-event {
        staging time-interval 300;
    }
    policy staging {
        events staging;
        then {
            execute-commands {
                commands {
                    "op url ftp://192.168.10.1/slax/ztp.slax";
                }
            }
        }
    }
}
