system {
    host-name staging-in-progress;
    root-authentication {
        encrypted-password "$6$CllakEoh$BKRPNFQG1y.m/twapqGV6gr5dwH2km8yCUrn9iSsGk3peCaRTt4/jLN9V0v5eSttGPeksPRFlZ3SvtgUw9Lvp1";
    }
    login {
        idle-timeout 30;
        class FULL-ACCESS {
            idle-timeout 30;
            login-alarms;
            permissions all;
            cli {
                timestamp;
            }
        }
        user admin {
            uid 2013;
            class FULL-ACCESS;
            authentication {
                encrypted-password "$6$NgvmIJVf$6OJJ2cMgNKEAQDmmRUQZ.vf7x4RXCuj8U/sNUW.6dXm/JW0CERb1Xtm59ejsvCOb46QNETgmg6I722UCPn1Yf0";
            }
        }
        user remote {
            full-name "All remote users";
            uid 2001;
            class FULL-ACCESS;
        }
    }
    services {
        netconf {
            ssh;
            rfc-compliant;
        }
        ssh {
            protocol-version v2;
            sftp-server;
            client-alive-count-max 3;
            client-alive-interval 30;
            connection-limit 8;
            rate-limit 10;
        }
    }
    auto-snapshot;
    domain-name home.com;
    time-zone America/Los_Angeles;
    authentication-order password;
    ports {
        console log-out-on-disconnect;
    }
}
snmp {
    community public {
        authorization read-only;
    }
}
chassis {
    alarm {
        management-ethernet {
            link-down ignore;
        }
    }
}
event-options {
    generate-event {
        staging time-interval 120;
    }
    policy staging {
        events staging;
        then {
            execute-commands {
                commands {
                    "op url ftp://192.168.10.1/slax/ztp.slax";
                }
            }
        }
    }
}
interfaces {
    me0 {
        unit 0 {
            family inet {
                dhcp {
                    vendor-id juniper-access;
                }
            }
        }
    }
    irb {
        unit 0 {
            family inet {
                dhcp {
                    vendor-id juniper-access;
                }
            }
        }
    }
}
