system {
    login {
        class FULL-ACCESS {
            idle-timeout 30;
            login-alarms;
            permissions all;
			cli {
                timestamp;
            }
        }
        class READ-ACCESS {
            idle-timeout 30;
            login-alarms;
            permissions [ firewall interface network routing system view view-configuration ];
            allow-commands "show log|clear interfaces statistics";
            deny-commands "(ssh)|(telnet)";
        }
        user admin {
            uid 2001;
            class FULL-ACCESS;
            authentication {
                encrypted-password "$6$NgvmIJVf$6OJJ2cMgNKEAQDmmRUQZ.vf7x4RXCuj8U/sNUW.6dXm/JW0CERb1Xtm59ejsvCOb46QNETgmg6I722UCPn1Yf0";
            }
        }
        user remote {
            full-name "TACACS Account for Shared Access";
            uid 2000;
            class FULL-ACCESS;
        }
    }
    root-authentication {
        encrypted-password "$6$CllakEoh$BKRPNFQG1y.m/twapqGV6gr5dwH2km8yCUrn9iSsGk3peCaRTt4/jLN9V0v5eSttGPeksPRFlZ3SvtgUw9Lvp1";
    }
    host-name staging-in-progress;
}
event-options {
    generate-event {
        staging time-interval 120;
    }
    policy staging {
        events staging;
        then {
            execute-commands {
                commands {
                    "op url ftp://192.168.10.1/slax/ztp.slax";
                }
            }
        }                               
    }
}
interfaces {
    me0 {
        unit 0 {
           family inet {
              dhcp {
                  vendor-id juniper-access;
                 }
             }
         }
    }
}
